name: Deploy SAM + Glue (All Envs)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
          
      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
            
      - name: Install SAM CLI
        run: pip install aws-sam-cli

      - name: Set Environment
        id: env
        run: |
          if [[ "${GITHUB_REF_NAME}" == "dev" ]]; then
            echo "env=dev" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF_NAME}" == "qa" ]]; then
            echo "env=qa" >> $GITHUB_OUTPUT
          else
            echo "env=prod" >> $GITHUB_OUTPUT
          fi

      - name: Upload Glue Script to S3
        run: |
          aws s3 cp glue/scripts/order_etl.py \
            s3://my-artifact-bucket-cicd/glue/scripts/order_etl.py

      - name: SAM Build
        run: sam build

      - name: SAM Deploy
        run: sam deploy --config-env ${{ steps.env.outputs.env }}
